services:
  qbittorrent-nox:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent
    #vvorth:smbshare
    user: 1000:1001
    environment:
      - QBT_LEGAL_NOTICE=confirm
      - QBT_VERSION=latest
      - QBT_TORRENTING_PORT=6881
      - QBT_WEBUI_PORT=8080
      - TZ=Asia/Tashkent
    env_file:
      - .secrets
    volumes:
      - /srv/media/to_download:/torrents:rw
      - ./config:/config:rw
      - /srv/media/:/downloads:rw
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          memory: 384M

    labels:
      - homepage.group=Media
      - homepage.name=QBittorrent
      - homepage.description=Torrent client
      - homepage.icon=qbittorrent
      - homepage.href=http://localhost:8080
      - homepage.statusStyle=dot
      - homepage.showStats=true
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://qbittorrent:8080
      - homepage.widget.username=${QB_USER}
      - homepage.widget.password=${QB_PASSWORD}
      - homepage.widget.fields=["download","upload"]
      # optional extras for this widget specifically:
      - homepage.widget.enableLeechProgress=true   # defaults false
      - homepage.widget.enableLeechSize=true

