
name: stack-c2

include:
  - ./homepage/compose.yaml
  - ./jellyfin/compose.yaml
  #- ./linkding/compose.yaml
  - ./pihole/compose.yaml
  #- ./hermes/compose.yaml
  #- ./ollama/compose.yaml
  #- ./n8n/compose.yaml
  #- ./traefik/compose.yaml
  - ./qbittorrent/compose.yaml
  - ./uptime-kuma/compose.yaml
  - ./ollama/compose.yaml

 
