services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: cube,cube.netbird.cloud,cube.newt-in.ts.net,192.168.0.14,172.17.17.191 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      #PUID: 1000 # optional, your user id
      #PGID: 1000 # optional, your group id
    ports:
      - 80:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./custom.js:/app/config/custom.js:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
