services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      TZ: ${TZ}
    # ports:
    #   - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # define route
      - "traefik.http.routers.linkding.rule=Host(`linkding.vvorth.org`)"
      - "traefik.http.routers.linkding.entrypoints=websecure"
      - "traefik.http.routers.linkding.tls.certresolver=cloudflare"
      # example if more than one port needed these two options are needed
      - "traefik.http.routers.linkding.service=linkding"
      - "traefik.http.services.linkding.loadbalancer.server.port=9090"
    
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
