services:
  jellyfin:
    container_name: jellyfin
    #image: jellyfin/jellyfin:latest
    #image: jellyfin/jellyfin:10.11.11
    image: jellyfin/jellyfin:12.0-rc3
    #apps-media:Media
    restart: unless-stopped
    #nobody:smbshare
    user: 1000:1001
    environment:
      TZ: ${TZ}
      RUSTICL_ENABLE: 'radeonsi'
    env_file:
      - .secrets
    ports:
      - 8096:8096/tcp
    volumes:
      - ./config:/config:rw
      - ./cache:/cache:rw
      - ${MEDIA_PATH}:/media:ro
    #transcoding
    devices:
      - "/dev/dri:/dev/dri"
    group_add:
      - "989"
    
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin Cube
      - homepage.description=Media Library
      - homepage.icon=jellyfin
      - homepage.href=http://localhost:8096
      - homepage.statusStyle=dot
      - homepage.showStats=true
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.fields=["movies","series","episodes"]
      - homepage.widget.enableBlocks=true       # library count blocks are OFF by default
      - homepage.widget.enableNowPlaying=true   # "now playing" is ON by default


