---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Cube Homepage
customJS: custom.js

layout:
  Media:
    style: column
    columns: 1
  Tools:
    style: column
    columns: 1
